---
- name: copy named.conf file
  template:
    src: templates/named.conf.j2
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
  notify: restart named
- name: copy zone file
  template:
    src: templates/direct.zone.j2
    dest: "/var/named/{{ cluster_domain }}.zone"
    mode: 0640
    owner: root
    group: named
  notify: restart named
- name: copy reverse zone file
  template:
    src: templates/reverse.zone.j2
    dest: "/var/named/{{ cluster_reverse_net }}.zone"
    mode: 0640
    owner: root
    group: named
  notify: restart named
- name: enable and start named service
  service:
    name: named
    state: started
    enabled: true
...
